### ISSUE TITLE
Leave your suggestions, compliments, criticisms or whatever suits you.

### ISSUE THREAD

**Issue by williamcanin** [williamcanin/chameleon-theme-jekyll#1]
Opine on the Chameleon Jek!

**Comment by falzar** [comment]
Can you help me please -> rake glup:serve result:

[19:18:27] Starting 'url_dev'...
[19:18:27] Starting 'javascripts'...
[19:18:27] Finished 'javascripts' after 12 ms
[19:18:27] Starting 'stylesheets'...
[19:18:27] Finished 'stylesheets' after 4.41 ms
[19:18:27] Starting 'jekyll-build'...
sed: 1: "_config.yml": invalid command code _
[19:18:27] 'url_dev' errored after 50 ms
[19:18:27] Error: Command `sed -i 's|^url: .*|url: "http://0.0.0.0:4000"|g' _config.yml` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.101 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[19:18:29] Finished 'jekyll-build' after 2.11 s

**Comment by williamcanin** [comment]
#falzar

1 - What operating system are you using? If Windows, be sure to use the terminal Git. The sed command will be executed.
2 - The error was in the function of the output "url_dev", which uses sed to change the variable "url" and "baseur" in "_config.yml" file. Do not change variables position, of file "_config.yml", changing only their values. The spaces have much importance.
